# Created January 30, 2007 (Shang-Wen Cheng)
#
# Effector descriptions.
#
vars:
  _effectors.commonPath: "${rainbow.path}/system/effectors"

effectors:
  SetFidelity:
    location: "${customize.system.target.0}"
    type: script
    scriptInfo:
      path    : "${_effectors.commonPath}/changeFidelity.pl"
      argument: "-l {fidelity}"
  ActivateServer:
    location: "${customize.system.target.0}"
    type: script
    scriptInfo:
      path    : "${_effectors.commonPath}/turnServer.pl"
      argument: "-s on"
  DeactivateServer:
    location: "${customize.system.target.0}"
    type: script
    scriptInfo:
      path    : "${_effectors.commonPath}/turnServer.pl"
      argument: "-s off"
  RandomReject:
    location: "${customize.system.target.0}"
    type: script
    scriptInfo:
      path    : "${_effectors.commonPath}/setRandomReject.pl"
      argument: "-r {frequency}"
  KillDelegate:
    location: "${customize.system.target.0}"
    type: java
    javaInfo:
      class   : org.sa.rainbow.translator.effectors.KillDelegateEffector
      argument: "{0}"
