#
# Gauge Type and Gauge Instance Specifications
#  - time periods generally in milliseconds
#
#
gauge-types:

  ResponseTimeGaugeT:
    values:
      end2endRespTime : double
    setupParams:
      targetIP:
        type:    String
        default: "localhost"
      beaconPeriod:
        type:    long
        default: 30000
      javaClass:
        type:    String
        default: "ar.uba.dc.thesis.znn.gauges.End2EndRespTimeGaugeWithStimulus"
    configParams:
      samplingFrequency:
        type:    long
        default: 1000
      targetProbeType:
        type:    String
        default: ~
    comment: "ResponseTimeGaugeWithStimulusT measures and reports the end-to-end response time from a client stimulus or its proxy."

gauge-instances:

  EERTG1:
    type:  ResponseTimeGaugeT
    model: "ZNewsSys:Acme"
    mappings:
      "end2endRespTimeWithStimulus(delegate.oracle)" : ClientT.experRespTime
    setupValues:
      targetIP: "${customize.system.target.0}"
    configValues:
      samplingFrequency: 1000
      targetProbeType  : clientproxywithstimulus
    comment: "EERTG1 is associated with the client component of the System, ZNewsSys, defined as an Acme model"