#
# Probe descriptions.
#
#

probes:
  ClientProxyProbe0:
    alias: clientproxywithstimulus
    location: "${customize.system.target.0}"
    type: java
    javaInfo:
      class: ar.uba.dc.thesis.znn.probes.ClientProxyProbeWithStimulus
      period: 2000
      args.length: 2
      args.0: "http://delegate.oracle/"
      args.1: "GetNewsContentClientStimulus"
